/* Generated by AN DISI Unibo */ 
package it.unibo.ping

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Ping ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var N = 1 
				val TMAX = 1500L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblue("$name STARTS ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="handleBall", cond=doswitch() )
				}	 
				state("handleBall") { //this:State
					action { //it:State
						delay(500) 
						CommUtils.outblue("$name sending ball n. $N ")
						forward("ball", "ball($N)" ,"pong" ) 
						 N = N + 1  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleBall", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleBall", TMAX )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="endofexchange",cond=whenTimeout("local_tout_"+name+"_handleBall"))   
					transition(edgeName="t01",targetState="handleBall",cond=whenDispatch("ball"))
				}	 
				state("endofexchange") { //this:State
					action { //it:State
						CommUtils.outblue("$name ENDS ")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
