/* Generated by AN DISI Unibo */ 
package it.unibo.pong

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Pong ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		  val TMAX = 1500L  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name STARTS  ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handleBall",cond=whenDispatch("ball"))
				}	 
				state("handleBall") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ball(N)"), Term.createTerm("ball(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								delay(500) 
								 val BallNumber = payloadArg(0).toInt()  
								CommUtils.outmagenta("$name receiving ball n. $BallNumber ")
								forward("ball", "ball($BallNumber)" ,"ping" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleBall", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleBall", TMAX )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="endofexchange",cond=whenTimeout("local_tout_"+name+"_handleBall"))   
					transition(edgeName="t04",targetState="handleBall",cond=whenDispatch("ball"))
				}	 
				state("endofexchange") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name ENDS ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
